name: Release
on:
  release:
    types:
      - prereleased
      - released
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            dist-target: 'macos'
          - os: ubuntu-latest
            dist-target: 'linux'
          - os: windows-latest
            dist-target: 'windows'
      fail-fast: false
    steps:
      - uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          ref: ${{ github.sha }}
          checkName: test
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install --no-install-recommends -y libarchive-tools
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm run dist:${{ matrix.dist-target }} -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
