name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            dist-target: linux
          - os: macos-latest
            dist-target: macos
          - os: windows-latest
            dist-target: windows
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install --no-install-recommends -y libarchive-tools
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Build and publish
        run: npm run dist:${{ matrix.dist-target }} -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
